sudo: required
dist: xenial
before_install:
  # - sudo apt-get install 

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make