# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: docker://nvidia/cuda:9.2-devel-ubuntu16.04

    - name: Build and Test
      run: |
        sudo apt install -y libglm-dev libassimp-dev libboost-graph-dev
        OMP_NUM_THREADS=4
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release .. && make
        cmake -DCMAKE_BUILD_TYPE=Release -DMANIFOLD_USE_OMP=ON .. && make
        cd test
        ./manifold_test
      
