# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: docker://nvidia/cuda:9.2-devel-ubuntu16.04

    - name: Install CMake
      run: |
        apt-get -y install wget libssl-dev
        version=3.17
        build=3
        mkdir ~/temp
        cd ~/temp
        wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
        tar -xzvf cmake-$version.$build.tar.gz
        cd cmake-$version.$build/
        ./bootstrap
        make -j$(nproc)
        make install
    - name: Install dependencies
      run: |
        sudo apt install -y libglm-dev libassimp-dev libboost-graph-dev
    - name: Build CUDA
        run: |
        mkdir buildCUDA
        cd buildCUDA
        cmake -DCMAKE_BUILD_TYPE=Release .. && make
    - name: Build OMP
      run: |
        OMP_NUM_THREADS=4
        mkdir buildOMP
        cd buildOMP
        cmake -DCMAKE_BUILD_TYPE=Release -DMANIFOLD_USE_OMP=ON .. && make
    - name: Test OMP
      run: |
        cd test
        ./manifold_test
      
